export const games = [

    {   
        id:1,
        name:"God Of War 4",
        date:"20/4/2018",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5, PC",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image:"https://image.api.playstation.com/vulcan/img/rnd/202010/2217/KAmUQWQ5V9QF3XDzmty1VkKj.png?w=1920&thumb=false",
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/god-of-war-screen-06-ps4-us-12jun17?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/god-of-war-screen-05-ps4-us-12jun17?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/god-of-war-screen-03-ps4-us-13jun16?$1600px$"],
        gameplay: ["https://gmedia.playstation.com/is/content/SIEPDC/global_pdc/en/games/pdps/g/go/god-of-war/video/god-of-war-axe-gameplay-01-ps4-us-30oct17.mp4"]
    },
    {
        id:2,
        name:"Spider-Man: Miles Morales",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: "https://gmedia.playstation.com/is/image/SIEPDC/spiderman-miles-morales-screenshot-03-disclaimer-en-01oct20?$1600px--t$",
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/spiderman-miles-morales-screenshot-01-disclaimer-en-01oct20?$1600px--t$", "https://gmedia.playstation.com/is/image/SIEPDC/spiderman-miles-morales-screenshot-04-disclaimer-en-01oct20?$1600px--t$", "https://gmedia.playstation.com/is/image/SIEPDC/spiderman-miles-morales-screenshot-02-disclaimer-en-01oct20?$1600px--t$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:3,
        name:"Gran Turismo 7",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/ap/rnd/202109/1321/y7iyxoBE8VKotN89QCFhLgLM.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:4,
        name:"Horizon Zero Dawn",
        date:"05/12/2017",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4",
        synopsis:"Take on the role of skilled hunter Aloy as you explore a lush world inhabited by mysterious creatures in a thrilling new open-world action/RPG game exclusive to the PlayStation®4 system. A lush post-apocalyptic world. How have machines taken over this world and what do they intend? What happened to the civilization that inhabited this place? Search every corner of a kingdom filled with ancient relics and mysterious buildings to unravel the past and unearth the many secrets of a forgotten land. Challenge dire odds: Combat in Horizon Zero Dawn is based on Aloy's speed and wits against the brute strength and size of machines. To defeat a much larger and technologically superior enemy, Aloy must use all her knowledge, in addition to her wits and agility, to survive each confrontation.",
        genre:"Action, RPG",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202009/2923/LyLrdlIfqiVzvynWJGtNfbU8.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:5,
        name:"Uncharted The Lost Legacy",
        date:"28/01/2022",
        distributor:"Sony Interactive Entertainment",
        platform:"PS5",
        synopsis:"Pursue your legacy and make your mark in UNCHARTED: Legacy of Thieves Collection. Experience Naughty Dog's gripping cinematic storytelling and the biggest action scenes from this iconic franchise. Discover a lost past with charismatic and complex thieves Nathan Drake and Chloe Frazer as they travel the world in search of extraordinary adventures and forgotten stories. UNCHARTED: Legacy of Thieves Collection includes the acclaimed single-player adventures from UNCHARTED™ 4: A Thief's End and UNCHARTED™: The Lost Legacy, remastered for the PS5™ console with stunning detail, enhanced graphics and frame rates.",
        genre:"Action, Adventure",
        image: 'https://image.api.playstation.com/vulcan/ap/rnd/202111/2000/aUGpwPrY0qZZ4CYGlLX3rtqr.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/uncharted-legacy-of-thieves-screenshot-21-en-10jan22?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/uncharted-legacy-of-thieves-screenshot-22-en-10jan22?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/uncharted-legacy-of-thieves-screenshot-24-en-10jan22?$1600px$"],
        gameplay: ["https://youtu.be/F3Wl-OiZCO4"]
    },
    {
        id:6,
        name:"Demon's Souls",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202011/1717/brIXKBE5BqYgBSrsDn6Wo18O.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:7,
        name:"Returnal",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/ap/rnd/202011/1621/oE5NHcrITZnKa1kYSCQtsoRE.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:8,
        name:"The Last of Us Remastered",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202010/2716/wYq1UsVEyQp6dT6cS1omgKiJ.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:9,
        name:"Spiderman: Game of the Year",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202011/0714/Cu9fyu6DM41JPekXLf1neF9r.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:10,
        name:"Bloodborn",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202010/2122/be8KRtoQ1dCjo9eixD7O66uc.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {   
        id:11,
        name:"Ghost of Tsushima",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/ap/rnd/202106/2322/FEhFbXbOMnlh1y8Mi9dPuJHQ.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:12,
        name:"Until Dawn",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202010/2621/OluGSoGnGcYHOQZ6AHExppNq.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:13,
        name:"Gran Turismo Sport",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202010/1520/s4OPcy23WwDCq1J4DAB6lS8g.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:14,
        name:"Horizon Forbidden West",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/ap/rnd/202010/2915/SqRcyLjZbpK26ej6TnWf43xp.jpg?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:15,
        name:"God of War III Remastered",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202010/2917/qKv4pRqoGFvnoUKyDSLg17ne.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:16,
        name:"Elden Ring",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/oPW9a7e3eZSZEiURXGegt6Lb.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    },
    {
        id:17,
        name:"Infamous Second Son",
        date:"12/11/2020",
        distributor:"Sony Interactive Entertainment",
        platform:"PS4, PS5",
        synopsis:"Kratos is a father again. As the mentor and protector of Atreus, a son determined to earn his respect, he is forced to face and control the rage that has long defined him as he travels through a menacing world with his son. With revenge against the Olympian gods in the past, Kratos now lives in the realm of Norse deities and monsters. It is in this harsh and merciless world that he must fight to survive while teaching his son to do the same and trying to stop him from repeating the cruel mistakes of the Ghost of Sparta. This stunning reimagining of God of War takes all the hallmarks of that famous franchise—brutal combat, epic boss fights, and breathtaking grandeur—and blends them into a powerful and gripping narrative that re-establishes the world of Kratos.",
        genre:"Action",
        image: 'https://image.api.playstation.com/vulcan/img/rnd/202010/2122/LbSCli0LHy5Ou5yRfts6X7UB.png?w=1920&thumb=false',
        screenshots: ["https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-02-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-08-disclaimer-en-01oct20?$1600px$", "https://gmedia.playstation.com/is/image/SIEPDC/gran-turismo-7-screenshot-07-disclaimer-en-01oct20?$1600px$"],
        gameplay: ["https://youtu.be/JsNgEBb4ZD0"]
    }

]